name: 'Deploy to Production'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (enter "production" to deploy)'
        required: true
env:
  AWS_REGION: us-west-2

concurrency: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy -s production
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
